package com.example.book_flight_mcp.constants;

import com.example.book_flight_mcp.model.Airlines;
import com.example.book_flight_mcp.model.Airport;

import java.util.Arrays;
import java.util.List;

public class FlightConstant {

    private static final List<Airlines> airlinesList = Arrays.asList(
            new Airlines("Aegean Airlines", "A3", "Greece"),
            new Airlines("Aer Lingus", "EI", "Ireland"),
            new Airlines("Aeroflot", "SU", "Russia"),
            new Airlines("Aerolineas Argentinas", "AR", "Argentina"),
            new Airlines("Aeroméxico", "AM", "Mexico"),
            new Airlines("Air Arabia", "G9", "United Arab Emirates"),
            new Airlines("Air Astana", "KC", "Kazakhstan"),
            new Airlines("Air Baltic", "BT", "Latvia"),
            new Airlines("Air Canada", "AC", "Canada"),
            new Airlines("Air China", "CA", "China"),
            new Airlines("Air Dolomiti", "EN", "Italy"),
            new Airlines("Air Europa", "UX", "Spain"),
            new Airlines("Air France", "AF", "France"),
            new Airlines("Air India", "AI", "India"),
            new Airlines("Air India Express", "IX", "India"),
            new Airlines("Air Japan", "NQ", "Japan"),
            new Airlines("Air Macau", "NX", "Macau (China)"),
            new Airlines("Air Malta", "KM", "Malta"),
            new Airlines("Air Mauritius", "MK", "Mauritius"),
            new Airlines("Air New Zealand", "NZ", "New Zealand"),
            new Airlines("Air Niugini", "PX", "Papua New Guinea"),
            new Airlines("Air Serbia", "JU", "Serbia"),
            new Airlines("Air Seychelles", "HM", "Seychelles"),
            new Airlines("Air Tahiti Nui", "TN", "French Polynesia"),
            new Airlines("Air Transat", "TS", "Canada"),
            new Airlines("AirAsia", "AK", "Malaysia"),
            new Airlines("AirAsia X", "D7", "Malaysia"),
            new Airlines("Alaska Airlines", "AS", "United States"),
            new Airlines("Alitalia", "AZ", "Italy"),
            new Airlines("All Nippon Airways – ANA", "NH", "Japan"),
            new Airlines("American Airlines", "AA", "United States"),
            new Airlines("Asiana Airlines", "OZ", "South Korea"),
            new Airlines("Austrian Airlines", "OS", "Austria"),
            new Airlines("Avianca", "AV", "Colombia"),
            new Airlines("Azerbaijan Airlines", "J2", "Azerbaijan"),
            new Airlines("Bamboo Airways", "QH", "Vietnam"),
            new Airlines("Bangkok Airways", "PG", "Thailand"),
            new Airlines("Batik Air", "ID", "Indonesia"),
            new Airlines("Belavia", "B2", "Belarus"),
            new Airlines("Biman Bangladesh Airlines", "BG", "Bangladesh"),
            new Airlines("British Airways", "BA", "United Kingdom"),
            new Airlines("Brussels Airlines", "SN", "Belgium"),
            new Airlines("Bulgaria Air", "FB", "Bulgaria"),
            new Airlines("Cathay Pacific", "CX", "Hong Kong"),
            new Airlines("Cebu Pacific", "5J", "Philippines"),
            new Airlines("China Airlines", "CI", "Taiwan"),
            new Airlines("China Eastern Airlines", "MU", "China"),
            new Airlines("China Southern Airlines", "CZ", "China"),
            new Airlines("Condor", "DE", "Germany"),
            new Airlines("Copa Airlines", "CM", "Panama"),
            new Airlines("Croatia Airlines", "OU", "Croatia"),
            new Airlines("Czech Airlines", "OK", "Czech Republic"),
            new Airlines("Delta Air Lines", "DL", "United States"),
            new Airlines("EasyJet", "U2", "United Kingdom"),
            new Airlines("EgyptAir", "MS", "Egypt"),
            new Airlines("EL AL Israel Airlines", "LY", "Israel"),
            new Airlines("Emirates", "EK", "United Arab Emirates"),
            new Airlines("Ethiopian Airlines", "ET", "Ethiopia"),
            new Airlines("Etihad Airways", "EY", "United Arab Emirates"),
            new Airlines("Eurowings", "EW", "Germany"),
            new Airlines("Eva Air", "BR", "Taiwan"),
            new Airlines("Fiji Airways", "FJ", "Fiji"),
            new Airlines("Finnair", "AY", "Finland"),
            new Airlines("Flynas", "XY", "Saudi Arabia"),
            new Airlines("Frontier Airlines", "F9", "United States"),
            new Airlines("Garuda Indonesia", "GA", "Indonesia"),
            new Airlines("Gol Linhas Aéreas", "G3", "Brazil"),
            new Airlines("Gulf Air", "GF", "Bahrain"),
            new Airlines("Hainan Airlines", "HU", "China"),
            new Airlines("Hawaiian Airlines", "HA", "United States"),
            new Airlines("Iberia", "IB", "Spain"),
            new Airlines("IndiGo", "6E", "India"),
            new Airlines("Interjet", "4O", "Mexico"),
            new Airlines("Iran Air", "IR", "Iran"),
            new Airlines("Iraqi Airways", "IA", "Iraq"),
            new Airlines("ITA Airways", "AZ", "Italy"),
            new Airlines("Japan Airlines", "JL", "Japan"),
            new Airlines("Jeju Air", "7C", "South Korea"),
            new Airlines("Jet2.com", "LS", "United Kingdom"),
            new Airlines("JetBlue Airways", "B6", "United States"),
            new Airlines("Kenya Airways", "KQ", "Kenya"),
            new Airlines("KLM Royal Dutch Airlines", "KL", "Netherlands"),
            new Airlines("Korean Air", "KE", "South Korea"),
            new Airlines("Kuwait Airways", "KU", "Kuwait"),
            new Airlines("LATAM Airlines", "LA", "Chile"),
            new Airlines("LOT Polish Airlines", "LO", "Poland"),
            new Airlines("Lufthansa", "LH", "Germany"),
            new Airlines("Luxair", "LG", "Luxembourg"),
            new Airlines("Malaysia Airlines", "MH", "Malaysia"),
            new Airlines("Middle East Airlines – MEA", "ME", "Lebanon"),
            new Airlines("Nepal Airlines", "RA", "Nepal"),
            new Airlines("Nok Air", "DD", "Thailand"),
            new Airlines("Norwegian Air Shuttle", "DY", "Norway"),
            new Airlines("Oman Air", "WY", "Oman"),
            new Airlines("Pakistan International Airlines", "PK", "Pakistan"),
            new Airlines("Philippine Airlines", "PR", "Philippines"),
            new Airlines("Qantas", "QF", "Australia"),
            new Airlines("Qatar Airways", "QR", "Qatar"),
            new Airlines("Royal Air Maroc", "AT", "Morocco"),
            new Airlines("Royal Jordanian", "RJ", "Jordan")
    );

    public static final List<Airport> airportList =  Arrays.asList(
            new Airport("ATL", "Hartsfield–Jackson Atlanta International Airport", "Atlanta"),
            new Airport("AKL", "Auckland Airport", "Auckland"),
            new Airport("AMS", "Amsterdam Schiphol Airport", "Amsterdam"),
            new Airport("ANC", "Ted Stevens Anchorage International Airport", "Anchorage"),
            new Airport("ATH", "Athens International Airport", "Athens"),
            new Airport("AUH", "Abu Dhabi International Airport", "Abu Dhabi"),
            new Airport("BCN", "Barcelona–El Prat Airport", "Barcelona"),
            new Airport("BKK", "Suvarnabhumi Airport", "Bangkok"),
            new Airport("BLR", "Kempegowda International Airport", "Bengaluru"),
            new Airport("BNE", "Brisbane Airport", "Brisbane"),
            new Airport("BOG", "El Dorado International Airport", "Bogotá"),
            new Airport("BOM", "Chhatrapati Shivaji Maharaj International Airport", "Mumbai"),
            new Airport("BOS", "Logan International Airport", "Boston"),
            new Airport("BRU", "Brussels Airport", "Brussels"),
            new Airport("BUD", "Budapest Ferenc Liszt International Airport", "Budapest"),
            new Airport("CAI", "Cairo International Airport", "Cairo"),
            new Airport("CAN", "Guangzhou Baiyun International Airport", "Guangzhou"),
            new Airport("CDG", "Paris Charles de Gaulle Airport", "Paris"),
            new Airport("CGK", "Soekarno–Hatta International Airport", "Jakarta"),
            new Airport("CLT", "Charlotte Douglas International Airport", "Charlotte"),
            new Airport("CMB", "Bandaranaike International Airport", "Colombo"),
            new Airport("CMN", "Mohammed V International Airport", "Casablanca"),
            new Airport("CPT", "Cape Town International Airport", "Cape Town"),
            new Airport("CPH", "Copenhagen Airport", "Copenhagen"),
            new Airport("DEL", "Indira Gandhi International Airport", "Delhi"),
            new Airport("DEN", "Denver International Airport", "Denver"),
            new Airport("DFW", "Dallas/Fort Worth International Airport", "Dallas–Fort Worth"),
            new Airport("DME", "Domodedovo International Airport", "Moscow"),
            new Airport("DOH", "Hamad International Airport", "Doha"),
            new Airport("DTW", "Detroit Metropolitan Wayne County Airport", "Detroit"),
            new Airport("DUB", "Dublin Airport", "Dublin"),
            new Airport("DUS", "Düsseldorf Airport", "Düsseldorf"),
            new Airport("DXB", "Dubai International Airport", "Dubai"),
            new Airport("EDI", "Edinburgh Airport", "Edinburgh"),
            new Airport("ESB", "Ankara Esenboğa Airport", "Ankara"),
            new Airport("EWR", "Newark Liberty International Airport", "Newark"),
            new Airport("FCO", "Leonardo da Vinci–Fiumicino Airport", "Rome"),
            new Airport("FLL", "Fort Lauderdale–Hollywood International Airport", "Fort Lauderdale"),
            new Airport("FRA", "Frankfurt am Main Airport", "Frankfurt"),
            new Airport("GDL", "Guadalajara International Airport", "Guadalajara"),
            new Airport("GIG", "Rio de Janeiro–Galeão International Airport", "Rio de Janeiro"),
            new Airport("GLA", "Glasgow Airport", "Glasgow"),
            new Airport("GRU", "São Paulo–Guarulhos International Airport", "São Paulo"),
            new Airport("GVA", "Geneva Airport", "Geneva"),
            new Airport("HEL", "Helsinki–Vantaa Airport", "Helsinki"),
            new Airport("HKG", "Hong Kong International Airport", "Hong Kong"),
            new Airport("HND", "Tokyo Haneda Airport", "Tokyo"),
            new Airport("IAD", "Washington Dulles International Airport", "Washington, D.C."),
            new Airport("IAH", "George Bush Intercontinental Airport", "Houston"),
            new Airport("ICN", "Incheon International Airport", "Seoul"),
            new Airport("IST", "Istanbul Airport", "Istanbul"),
            new Airport("JED", "King Abdulaziz International Airport", "Jeddah"),
            new Airport("JFK", "John F. Kennedy International Airport", "New York"),
            new Airport("JNB", "O. R. Tambo International Airport", "Johannesburg"),
            new Airport("KBP", "Boryspil International Airport", "Kyiv"),
            new Airport("KIX", "Kansai International Airport", "Osaka"),
            new Airport("KUL", "Kuala Lumpur International Airport", "Kuala Lumpur"),
            new Airport("LAS", "Harry Reid International Airport", "Las Vegas"),
            new Airport("LAX", "Los Angeles International Airport", "Los Angeles"),
            new Airport("LGA", "LaGuardia Airport", "New York"),
            new Airport("LHR", "London Heathrow Airport", "London"),
            new Airport("LGW", "London Gatwick Airport", "London"),
            new Airport("LIM", "Jorge Chávez International Airport", "Lima"),
            new Airport("LIS", "Lisbon Humberto Delgado Airport", "Lisbon"),
            new Airport("LJU", "Ljubljana Jože Pučnik Airport", "Ljubljana"),
            new Airport("LOS", "Murtala Muhammed International Airport", "Lagos"),
            new Airport("LPB", "El Alto International Airport", "La Paz"),
            new Airport("LYS", "Lyon–Saint-Exupéry Airport", "Lyon"),
            new Airport("MAD", "Adolfo Suárez Madrid–Barajas Airport", "Madrid"),
            new Airport("MAN", "Manchester Airport", "Manchester"),
            new Airport("MCO", "Orlando International Airport", "Orlando"),
            new Airport("MEL", "Melbourne Airport", "Melbourne"),
            new Airport("MEX", "Mexico City International Airport", "Mexico City"),
            new Airport("MIA", "Miami International Airport", "Miami"),
            new Airport("MNL", "Ninoy Aquino International Airport", "Manila"),
            new Airport("MRS", "Marseille Provence Airport", "Marseille"),
            new Airport("MSP", "Minneapolis–Saint Paul International Airport", "Minneapolis"),
            new Airport("MUC", "Munich Airport", "Munich"),
            new Airport("MXP", "Milan Malpensa Airport", "Milan"),
            new Airport("NBO", "Jomo Kenyatta International Airport", "Nairobi"),
            new Airport("NCE", "Nice Côte d’Azur Airport", "Nice"),
            new Airport("NGO", "Chubu Centrair International Airport", "Nagoya"),
            new Airport("NRT", "Tokyo Narita International Airport", "Tokyo"),
            new Airport("OKA", "Naha Airport", "Okinawa"),
            new Airport("ORD", "Chicago O’Hare International Airport", "Chicago"),
            new Airport("ORY", "Paris Orly Airport", "Paris"),
            new Airport("OSL", "Oslo Gardermoen Airport", "Oslo"),
            new Airport("OTP", "Henri Coandă International Airport", "Bucharest"),
            new Airport("PEK", "Beijing Capital International Airport", "Beijing"),
            new Airport("PER", "Perth Airport", "Perth"),
            new Airport("PHL", "Philadelphia International Airport", "Philadelphia"),
            new Airport("PHX", "Phoenix Sky Harbor International Airport", "Phoenix"),
            new Airport("PMI", "Palma de Mallorca Airport", "Palma de Mallorca"),
            new Airport("PRG", "Václav Havel Airport Prague", "Prague"),
            new Airport("PTY", "Tocumen International Airport", "Panama City"),
            new Airport("RUH", "King Khalid International Airport", "Riyadh"),
            new Airport("SAN", "San Diego International Airport", "San Diego"),
            new Airport("SCL", "Arturo Merino Benítez International Airport", "Santiago"),
            new Airport("SEA", "Seattle–Tacoma International Airport", "Seattle"),
            new Airport("SIN", "Singapore Changi Airport", "Singapore")
        );
    public static List<Airport> listOfAirports(){
        return airportList;
    }

    public static List<Airlines> listOfAirlines() {
        return airlinesList;
    }
}
